/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package verginiza;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    //declares relevant variables
    private static String pass;
    private static final String filepath = "src\\verginiza\\data_1.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();
    
    /*defines a public class name that contains a public static variable called uname
    so that it is possible to access uname through other classes.
    */
    public class name {

        public static String uname;
            
    }

    public LOGIN() {
        initComponents();
        setResizable(false); // set pane resize option into false (you cannot resize the pane).

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        JLBLUser = new javax.swing.JLabel();
        JLBLPass = new javax.swing.JLabel();
        JTFUser = new javax.swing.JTextField();
        JBTNClear = new javax.swing.JButton();
        JBTNLogin = new javax.swing.JButton();
        JPPass = new javax.swing.JPasswordField();
        JLBLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(50, 50, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Login"); // NOI18N

        JLBLUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLBLUser.setForeground(new java.awt.Color(255, 255, 255));
        JLBLUser.setText("Username:");

        JLBLPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLBLPass.setForeground(new java.awt.Color(255, 255, 255));
        JLBLPass.setText("Password:");

        JTFUser.setBackground(new java.awt.Color(102, 102, 102));
        JTFUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFUser.setForeground(new java.awt.Color(255, 255, 255));
        JTFUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUserActionPerformed(evt);
            }
        });

        JBTNClear.setText("Clear");
        JBTNClear.setToolTipText("");
        JBTNClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNClearActionPerformed(evt);
            }
        });

        JBTNLogin.setBackground(new java.awt.Color(0, 255, 255));
        JBTNLogin.setForeground(new java.awt.Color(0, 0, 0));
        JBTNLogin.setText("Login");
        JBTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNLoginActionPerformed(evt);
            }
        });

        JPPass.setBackground(new java.awt.Color(102, 102, 102));
        JPPass.setForeground(new java.awt.Color(255, 255, 255));
        JPPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPPassActionPerformed(evt);
            }
        });

        JLBLogin.setBackground(new java.awt.Color(255, 255, 255));
        JLBLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLBLogin.setForeground(new java.awt.Color(255, 255, 255));
        JLBLogin.setText("LOG IN ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verginiza/Screenshot_2025-02-25_102901-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(JBTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTNLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLBLPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPPass, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JLBLUser)
                                .addGap(18, 18, 18)
                                .addComponent(JTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(JLBLogin)))
                .addGap(77, 77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JLBLogin)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBLUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JPPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBLPass))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTNLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFUserActionPerformed

    private void JPPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPPassActionPerformed
        // TODO add your handling code here:asd
    }//GEN-LAST:event_JPPassActionPerformed

    private void JBTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNLoginActionPerformed
        //handling code when Login button is pressed.
        /*checks username and password against stored data.
          If the credentials match, it grants access to a menu.
        */
        try {
            name.uname = JTFUser.getText();
            pass = JPPass.getText();

            filecheck();

            int check = 0;

            /* checks if username and password are blank. If so, it shows a pane 
            that informs the user to type username and password.*/
            if (name.uname.isBlank() && pass.isBlank()) { 
                JOptionPane.showMessageDialog(null, "Please enter username and password.", "Message", JOptionPane.WARNING_MESSAGE);
            } else {
                for (int a = 0; a < userlist.size(); a++) {
                    JSONObject userobject = (JSONObject) userlist.get(a);
                    String foundusname = (String) userobject.get("username");
                    String foundpass = (String) userobject.get("password");
                    

                    if (name.uname.equals(foundusname) && pass.equals(foundpass)) {
                        check++;
                        Menu x = new Menu();
                        x.setVisible(true);
                        setVisible(false);

                        break;
                    } 
                }

                // If no match was found, show error message
                if (check == 0) {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password.", "Message", JOptionPane.ERROR_MESSAGE);
                }
            }
           
        } catch (Exception e) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, e); 
            /*catch almost all runtime errors, such as:
            NullPointerException
            IOException
            ParseException
            ArrayIndexOutOfBoundsException */
        }
    }//GEN-LAST:event_JBTNLoginActionPerformed

    private void JBTNClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNClearActionPerformed
        // This method is triggered when the "Clear" button (JBTNClear) is clicked  
        
        // Set the text field for username (JTFUser) to an empty string, effectively clearing it  
        JTFUser.setText("");
        
        // Set the password field (JPPass) to an empty string, removing any entered password  
        JPPass.setText("");
    }//GEN-LAST:event_JBTNClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);

            }
        });
    }

    public static void filecheck() throws FileNotFoundException, IOException, ParseException {
        
        // Create a FileReader to read the file specified by 'filepath'
        FileReader reader = new FileReader(filepath);

        // Check if the file is ready to be read 
        if (reader.ready()) {
            Scanner s = new Scanner(reader);
            String line = "";
            
            // Read the file line by line and store it in 'line' variable
            while (s.hasNext()) {
                line = line + s.nextLine();
            }

            // If the file is not empty, parse its contents
            if (!line.equals("")) {
                reader.close();
                
                // Create a new FileReader to read and parse JSON data
                FileReader reader2 = new FileReader(filepath);
                record = (JSONObject) jsonParser.parse(reader2);
                userlist = (JSONArray) record.get("data");
                reader2.close();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNClear;
    private javax.swing.JButton JBTNLogin;
    private javax.swing.JLabel JLBLPass;
    private javax.swing.JLabel JLBLUser;
    private javax.swing.JLabel JLBLogin;
    private javax.swing.JPasswordField JPPass;
    private javax.swing.JTextField JTFUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
