/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package verginiza;
//imports relevant packages

import javax.swing.JOptionPane;
import verginiza.LOGIN.name;

/**
 *
 * @author WIFI SERVER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Menu() {
        initComponents();
        setResizable(false); //prevents the user from resizing the window
        AccName.setText(name.uname + "!"); //Displays the logged-in user's name in the interface.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBTNUpd = new javax.swing.JButton();
        JBTNLogout = new javax.swing.JButton();
        JBTNAdd = new javax.swing.JButton();
        JBTNDelete = new javax.swing.JButton();
        AccName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(50, 50, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 26, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 613, -1));

        JBTNUpd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBTNUpd.setText("Update Student");
        JBTNUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNUpdActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 225, 233, 48));

        JBTNLogout.setBackground(new java.awt.Color(102, 0, 0));
        JBTNLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBTNLogout.setForeground(new java.awt.Color(255, 255, 255));
        JBTNLogout.setText("Log Out");
        JBTNLogout.setBorderPainted(false);
        JBTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 225, 233, 48));

        JBTNAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBTNAdd.setText("Add Student");
        JBTNAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNAddActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 151, 233, 48));

        JBTNDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBTNDelete.setText("Delete Student");
        JBTNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(JBTNDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 233, 48));

        AccName.setBackground(new java.awt.Color(255, 255, 255));
        AccName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AccName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(AccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 26, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTNUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNUpdActionPerformed
        //displays the update student window when pressed
        updateStudent1 upd = new updateStudent1(); //instantiates the updatestudent class 
        setVisible(false);//hide this window
        upd.setVisible(true);//this makes the update student window to show.
    }//GEN-LAST:event_JBTNUpdActionPerformed

    private void JBTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNLogoutActionPerformed
        //Displays a confirmation dialog for logout

        int confirm = JOptionPane.showConfirmDialog(rootPane, "Do you want to log out?", "Log out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            LOGIN l = new LOGIN();
            name.uname = null; // Reset username on interface 
            dispose(); // Close the current window completely
            l.setVisible(true);

        }
    }//GEN-LAST:event_JBTNLogoutActionPerformed

    private void JBTNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNDeleteActionPerformed
        // displays the delete student window
        deleteStudent a = new deleteStudent();
        a.setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_JBTNDeleteActionPerformed

    private void JBTNAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNAddActionPerformed
        //displays the add student window
        addStudent a = new addStudent();
        a.setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_JBTNAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccName;
    private javax.swing.JButton JBTNAdd;
    private javax.swing.JButton JBTNDelete;
    private javax.swing.JButton JBTNLogout;
    private javax.swing.JButton JBTNUpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
